name: my-check

on:
  push:
    branches: ['main']

jobs:
  Build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: make install
      - run: make lint
      - run: make test